### ISSUE TITLE
Don't push to main

### ISSUE THREAD

**Issue by RepublicOfMars** [CSAllenISDClassroom/scheduling-app-model-runtimeterror#6]
It creates extra work because:
- It's difficult to have multiple people pushing to one branch (especially main)
- It can delete other's work
- It makes it more difficult to merge
- It's more difficult to keep track of

What you should do:
- Make your own branch, and once you're done with your task make a pull request to merge it back (ask Enzo or Me if you don't want to resolve conflicts)
- Ask people to review your pull request if you aren't sure it's alright to merge (or if you're unsure of your changes) (this is an inbuilt feature of pull requests)

What you should *never* do:
- Merge your main branch into main. This overwrites the main branch with yours, deleting other's commits and merges. Sam's merge commits and my merge commits got deleted because someone did this.

**Comment by samuelsteele** [comment]
do not the main
